# Generated by Django 6.0 on 2025-12-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('pet_walking', 'Petwalking'), ('petsitting', 'Petsitting'), ('petgrooming', 'Petgrooming'), ('daycare', 'Daycare'), ('boarding', 'Boarding'), ('veterinary', 'Veterinary'), ('training', 'Training')], default='customer', max_length=50),
        ),
    ]
