# Generated by Django 6.0 on 2025-12-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0003_profile_address_profile_city_profile_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
