# Generated by Django 6.0 on 2025-12-14 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0004_remove_profile_address_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PetCare.profile')),
            ],
        ),
    ]
