# Generated by Django 6.0 on 2025-12-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('service_providers', 'Service Providers')], default='customer', max_length=50),
        ),
    ]
