# Generated by Django 6.0 on 2025-12-17 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0006_alter_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('provider_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization / Company')], max_length=20)),
                ('bio', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('travel_distance', models.PositiveIntegerField()),
                ('services', models.JSONField()),
                ('id_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('passport', 'Passport')], max_length=20)),
                ('id_proof', models.FileField(upload_to='providers/id/')),
                ('grooming_certificate', models.FileField(blank=True, upload_to='providers/certificates/')),
                ('vet_license', models.FileField(blank=True, upload_to='providers/certificates/')),
                ('training_certificate', models.FileField(blank=True, upload_to='providers/certificates/')),
                ('organization_registration', models.FileField(blank=True, upload_to='providers/certificates/')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
