# Generated by Django 6.0 on 2025-12-17 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0007_serviceprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PetCare.profile'),
        ),
    ]
