# Generated by Django 6.0 on 2025-12-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0008_remove_serviceprovider_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='travel_distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
