# Generated by Django 6.0 on 2025-12-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0009_alter_serviceprovider_travel_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='services',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
