# Generated by Django 6.0 on 2025-12-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0010_alter_serviceprovider_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='latitude',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='longitude',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
