# Generated by Django 6.0 on 2025-12-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0011_serviceprovider_latitude_serviceprovider_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
