# Generated by Django 6.0 on 2025-12-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0012_alter_serviceprovider_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
