# Generated by Django 6.0 on 2025-12-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0013_alter_serviceprovider_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='provider_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('organization', 'Organization / Company')], max_length=20, null=True),
        ),
    ]
