# Generated by Django 6.0 on 2025-12-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0014_alter_serviceprovider_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='grooming_certificate',
            field=models.FileField(blank=True, null=True, upload_to='providers/certificates/'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='providers/id/'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='organization_registration',
            field=models.FileField(blank=True, null=True, upload_to='providers/certificates/'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='training_certificate',
            field=models.FileField(blank=True, null=True, upload_to='providers/certificates/'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='vet_license',
            field=models.FileField(blank=True, null=True, upload_to='providers/certificates/'),
        ),
    ]
