# Generated by Django 6.0 on 2025-12-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0015_alter_serviceprovider_grooming_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='id_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('passport', 'Passport')], max_length=20, null=True),
        ),
    ]
