# Generated by Django 6.0 on 2025-12-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0016_alter_serviceprovider_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='id_number',
            field=models.CharField(blank=True, help_text='Government ID number', max_length=50, null=True, unique=True),
        ),
    ]
