# Generated by Django 6.0 on 2025-12-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0017_serviceprovider_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reason', models.TextField()),
                ('blacklisted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
