# Generated by Django 6.0 on 2025-12-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0018_blacklistedprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedprovider',
            name='reason',
            field=models.TextField(default='Violation of platform policies'),
        ),
    ]
