# Generated by Django 6.0 on 2026-01-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0019_alter_blacklistedprovider_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=30)),
                ('pet_name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('pet_photo', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetCare.customer')),
            ],
        ),
    ]
