# Generated by Django 6.0 on 2026-01-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0020_mypet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.PositiveIntegerField()),
                ('product_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='mypet',
            name='pet_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/pets/'),
        ),
    ]
