# Generated by Django 6.0 on 2026-01-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0021_petshop_alter_mypet_pet_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='petshop',
            name='product_category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petshop',
            name='product_description',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petshop',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
