# Generated by Django 6.0 on 2026-01-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0022_petshop_product_category_petshop_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petshop',
            name='pet_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
