# Generated by Django 6.0 on 2026-01-06 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0023_petshop_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petshop',
            name='pet_type',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Cats_and_Dogs', 'Cats and Dogs')], max_length=50),
        ),
        migrations.AlterField(
            model_name='petshop',
            name='product_image',
            field=models.FileField(upload_to='products/'),
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetCare.customer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetCare.serviceprovider')),
            ],
        ),
    ]
