# Generated by Django 6.0 on 2026-01-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0024_alter_petshop_pet_type_alter_petshop_product_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceBooking',
        ),
    ]
