# Generated by Django 6.0 on 2026-01-07 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0028_servicebooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicebooking',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='servicebooking',
            old_name='booked_at',
            new_name='booking_date',
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PetCare.payment'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
