# Generated by Django 6.0 on 2026-01-30 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0033_voicecommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PetCare.payment'),
        ),
    ]
