# Generated by Django 6.0 on 2026-02-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0034_alter_servicebooking_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
