# Generated by Django 6.0 on 2026-02-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCare', '0035_alter_serviceprovider_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='travel_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
